#!/usr/bin/env python3
"""Regenerate splash_frames.hpp from art/splash-load.png + art/splash-ignite.png.
96x72 px, rendered in-app as 96x36 chars via half-blocks."""
from PIL import Image
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
W, H = 96, 72

def arr(name):
    img = Image.open(ROOT / 'art' / f'{name}.png').convert('RGB').resize((W, H), Image.LANCZOS)
    data = list(img.getdata())
    flat = [c for px in data for c in px]
    return flat

def emit(f, sym, flat):
    f.write(f"static const unsigned char {sym}[{W}*{H}*3] = {{\n")
    for i in range(0, len(flat), 24):
        f.write("    " + ",".join(str(v) for v in flat[i:i+24]) + ",\n")
    f.write("};\n")

with open(ROOT / 'splash_frames.hpp', 'w') as f:
    f.write("// generated by tools/make_splash_frames.py from art/*.png; do not hand-edit\n")
    f.write("#pragma once\n\n")
    f.write(f"constexpr int SPLASH_W = {W}, SPLASH_H = {H};\n\n")
    emit(f, "SPLASH_LOAD", arr("splash-load"))
    f.write("\n")
    emit(f, "SPLASH_IGNITE", arr("splash-ignite"))
print("wrote splash_frames.hpp")
